{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-device-provider-gradle-proto",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-proto-30.1.1.jar",
          "url": "android-device-provider-gradle-proto-30.1.1.jar",
          "size": 38003,
          "sha512": "e885449af11a413b865659eb40200951d88fb3a174359ee395a719aa3a1c8bb7f5df4f4a4edfed7f4239a7f58523e7da528bc8c5fcfa8f9613489387f1b89666",
          "sha256": "125c0d1f33c5ef0320b604eec58c2db9b68b03afa394e8da04f16ddc9b3e565a",
          "sha1": "2c141ae30a764a865f6424afc48f3d4e0d848e15",
          "md5": "923a8d32ba91f9f340bfa6457726d327"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-device-provider-gradle-proto-30.1.1.jar",
          "url": "android-device-provider-gradle-proto-30.1.1.jar",
          "size": 38003,
          "sha512": "e885449af11a413b865659eb40200951d88fb3a174359ee395a719aa3a1c8bb7f5df4f4a4edfed7f4239a7f58523e7da528bc8c5fcfa8f9613489387f1b89666",
          "sha256": "125c0d1f33c5ef0320b604eec58c2db9b68b03afa394e8da04f16ddc9b3e565a",
          "sha1": "2c141ae30a764a865f6424afc48f3d4e0d848e15",
          "md5": "923a8d32ba91f9f340bfa6457726d327"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-proto-30.1.1-javadoc.jar",
          "url": "android-device-provider-gradle-proto-30.1.1-javadoc.jar",
          "size": 444344,
          "sha512": "2fac7bffe1bff1263a3dc7baa03f15db87cb19b1ded7c1f539865375910f4985ebb7b28dbc50714beeaf9abe7e3c1bc607dfde35e500e44a2ae2f65531a7eaa9",
          "sha256": "c41ff5e15a10b38c3da9c690a03266f50435c1e98c0da2eaa1a3d5e91588d827",
          "sha1": "4cf4057bd2c0ab4c4c8892d0360698363c81e8f1",
          "md5": "9d15db7d129471c1e4262263c6070596"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-proto-30.1.1-sources.jar",
          "url": "android-device-provider-gradle-proto-30.1.1-sources.jar",
          "size": 16990,
          "sha512": "9eb99c86e859407c3a307774068fd0e6758405a1ab230c81e32331bdb6a80ec736cde56e4bcc6dbac2dd02da27ba0f3616fa61b8523aec088c72b665acf1463a",
          "sha256": "115494679a077946a5682d709403fb8a594569ba9de9bceaec7a0786a9fba3f3",
          "sha1": "0dcebccbcc7c1908c19f984f5596008eeb3e67c1",
          "md5": "15803e8957e9f7f3ac887fed4ba40d77"
        }
      ]
    }
  ]
}
