{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.ddms",
    "module": "ddmlib",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "ddmlib-30.1.1.jar",
          "url": "ddmlib-30.1.1.jar",
          "size": 562875,
          "sha512": "c6f3da61e757e2982bbee3a5557a9a48ce1e3529bfbdfa10b5e200c8ebf5a3d3c6815e91c469925d12020f15d06338d52e1b041945c29270c03aa37b78c2caab",
          "sha256": "1881ada1800cae672fa405a47dc18a0d9a7bccbae0920d5c9859531e8ca03f95",
          "sha1": "9089fc46b26d1fef2ea115f454039ecdac400a32",
          "md5": "56f766464ab49a4ec73ceec5c8f77f61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "ddmlib-30.1.1.jar",
          "url": "ddmlib-30.1.1.jar",
          "size": 562875,
          "sha512": "c6f3da61e757e2982bbee3a5557a9a48ce1e3529bfbdfa10b5e200c8ebf5a3d3c6815e91c469925d12020f15d06338d52e1b041945c29270c03aa37b78c2caab",
          "sha256": "1881ada1800cae672fa405a47dc18a0d9a7bccbae0920d5c9859531e8ca03f95",
          "sha1": "9089fc46b26d1fef2ea115f454039ecdac400a32",
          "md5": "56f766464ab49a4ec73ceec5c8f77f61"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ddmlib-30.1.1-javadoc.jar",
          "url": "ddmlib-30.1.1-javadoc.jar",
          "size": 1180231,
          "sha512": "f5fb633a123bb17d2c0096504ee3a8124d1c816abd26f41a95a83b07420c48d27c6c07b09c7c4d50a75c9f6211c8bbd7c7a89098bf2d719aa7e8c221beb70dcc",
          "sha256": "c8ed64a70fd299d7d1e2189e8ee0bcbae0efb180954a7ff0012e98d0294eaec5",
          "sha1": "069b738c215c94a71350405c93549ee2aa8ca658",
          "md5": "7cc44ee28aae4cfc10ea936c0c1ee792"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ddmlib-30.1.1-sources.jar",
          "url": "ddmlib-30.1.1-sources.jar",
          "size": 690885,
          "sha512": "fe00e63a2b3427320676315be04551eb85c5ffa088823cf45a3efe58f85d8cee6b92c6ac7c606209871bd1bcd350149e7117d366188b62b3472f4e305330ef25",
          "sha256": "80910d0a4cc1d43e1ebc3481e95d95fef0fae9c9a53a8df60573bb83145a7ddd",
          "sha1": "b132a17bb9f8f35e3d427d96ff0e0fcbee1ac0d6",
          "md5": "573b34f3ff4dafbcb66ffba8b691db61"
        }
      ]
    }
  ]
}
