{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "7.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.1.1.jar",
          "url": "gradle-api-7.1.1.jar",
          "size": 234299,
          "sha512": "13f4616362683186210cb54ef00bbf5d828a08aa8f88d10515b960b26cebb5e39cd3579656df74656d1d1585e8be1070ca7ead2e23ce928e9f56ddc103f6d256",
          "sha256": "20661115362992d179a2211c3b0a35dcdcc71af00f9fcd663cd92d640d687cb1",
          "sha1": "a3cf4e4fa7e9be3752bb88aeb5e93dc0612a4d81",
          "md5": "5a60ca25e1d70520ee24fc2b0eae2eab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.1.1.jar",
          "url": "gradle-api-7.1.1.jar",
          "size": 234299,
          "sha512": "13f4616362683186210cb54ef00bbf5d828a08aa8f88d10515b960b26cebb5e39cd3579656df74656d1d1585e8be1070ca7ead2e23ce928e9f56ddc103f6d256",
          "sha256": "20661115362992d179a2211c3b0a35dcdcc71af00f9fcd663cd92d640d687cb1",
          "sha1": "a3cf4e4fa7e9be3752bb88aeb5e93dc0612a4d81",
          "md5": "5a60ca25e1d70520ee24fc2b0eae2eab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.1.1-javadoc.jar",
          "url": "gradle-api-7.1.1-javadoc.jar",
          "size": 464814,
          "sha512": "c8f9cd3d92a56d4817655a6a65292f5941cef9b73660a238fe9ea08364f50eb5edeb095267c52d0a5394884ee9883b13a4ab2072a3f4b006cd2176b3d39717a1",
          "sha256": "69e0f48d70d67bcec0c4d41400c9e25705d897f5f55351b98621343a3d013837",
          "sha1": "4f3b3fffa6d17e5ce0a19085052805334b947e27",
          "md5": "4fa65051a487edbbd379fe352e50b56a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.1.1-sources.jar",
          "url": "gradle-api-7.1.1-sources.jar",
          "size": 235381,
          "sha512": "1a640cebac5ae767b5a03385b5bb6ac498714dda443e6ee83034924a3314edd170a17a52efa266e5d89f185a69588643ea7eafa6aa02db9efa4559da3bc83d4c",
          "sha256": "0d595210233b85485401e35dbad9f77d53ca954ab73410481357175f7176b7f5",
          "sha1": "aedd7a3acd6b1ded3f2ca3eb297437c56423c5bf",
          "md5": "a5819142687b47def5904c88e59502b6"
        }
      ]
    }
  ]
}
