{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint-model",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lint-model-30.1.1.jar",
          "url": "lint-model-30.1.1.jar",
          "size": 158181,
          "sha512": "6d15ae942636829f54b748f0431d6b30c8903ec8c70a11d1eb97eefc33e65617218f3b0c4bfa7f947671e3bd44c92fbc5b27306ce18f3aa05d0fe47d54d75ce1",
          "sha256": "a4a862f3c3df45c541b155435f7b78b6fa66ad61e865f02f08d5a0f516326290",
          "sha1": "3cd8a1a00d80a4c4ff72a403502ffdd0456733e6",
          "md5": "e9d7a3b2dcdbaf5ffe88b0249768a86e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lint-model-30.1.1.jar",
          "url": "lint-model-30.1.1.jar",
          "size": 158181,
          "sha512": "6d15ae942636829f54b748f0431d6b30c8903ec8c70a11d1eb97eefc33e65617218f3b0c4bfa7f947671e3bd44c92fbc5b27306ce18f3aa05d0fe47d54d75ce1",
          "sha256": "a4a862f3c3df45c541b155435f7b78b6fa66ad61e865f02f08d5a0f516326290",
          "sha1": "3cd8a1a00d80a4c4ff72a403502ffdd0456733e6",
          "md5": "e9d7a3b2dcdbaf5ffe88b0249768a86e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-model-30.1.1-javadoc.jar",
          "url": "lint-model-30.1.1-javadoc.jar",
          "size": 261,
          "sha512": "76573c1dc43a3309f0368318866e5d421a0f924122457f63de14fa344922dd05596c34501d239c91af3d6db79ad97d56194d8d0cd88949f5c1c3577813842453",
          "sha256": "b67a2a2d1b453bfc71a132ee2e597db1570e22a839b7197f6a8900c6ba80e7cf",
          "sha1": "be88728de44480a44bd0dba63508983fd7962905",
          "md5": "02f6f3bcf881b1bb19e82e69bc21ef53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-model-30.1.1-sources.jar",
          "url": "lint-model-30.1.1-sources.jar",
          "size": 39593,
          "sha512": "6c683410fc23e48fb465709ee6265105945ab6d9418dbeaf140f3bb310e7888c02f545e533ea918e69b3f21c9e5088e172d14f004be3bcf1bcdc798135c36a94",
          "sha256": "06645f552370d29c47e404ef4e101dd1c2e164eb508f79ea0959902900b4b7e9",
          "sha1": "cf03f415432fa801aa786f82a3cf5043e370fb37",
          "md5": "90eba9bbd167fb545d04aca3e2623a14"
        }
      ]
    }
  ]
}
