{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "apkzlib",
    "version": "7.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "apkzlib-7.1.1.jar",
          "url": "apkzlib-7.1.1.jar",
          "size": 202884,
          "sha512": "0c9b55acddce10cf737f8c6cf1aabf5c7169b9384d597708c3f5b757c7a3a9fea1c451fd4d1e01a90c1732980497578b2a87a64065424e7da5a7434bd7e519a2",
          "sha256": "2c386bea4afbf28d8c23ae333e42f556a844cedb5090cbe005032d88cc6d1dfc",
          "sha1": "f33ce847854150059128ff21633e1135c3b8b10e",
          "md5": "632eda6025e5cc45de1b595a032b73a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-7.1.1.jar",
          "url": "apkzlib-7.1.1.jar",
          "size": 202884,
          "sha512": "0c9b55acddce10cf737f8c6cf1aabf5c7169b9384d597708c3f5b757c7a3a9fea1c451fd4d1e01a90c1732980497578b2a87a64065424e7da5a7434bd7e519a2",
          "sha256": "2c386bea4afbf28d8c23ae333e42f556a844cedb5090cbe005032d88cc6d1dfc",
          "sha1": "f33ce847854150059128ff21633e1135c3b8b10e",
          "md5": "632eda6025e5cc45de1b595a032b73a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-7.1.1-javadoc.jar",
          "url": "apkzlib-7.1.1-javadoc.jar",
          "size": 699549,
          "sha512": "c34f4039b488d860b1e9679fcd9045252ad0043ba09882fe3768a58d3fa5d8febbeb20e02f91b9fdfbd5cf8d338be73398d798f054a8f69c96657932c07d1c3f",
          "sha256": "99de721d285a665a93b4784ba08efdcb0f5e15c396ba51af52327e2eb3ce2a91",
          "sha1": "81d9b90150fb45e4d8e84cee1f2292816871acb1",
          "md5": "2df341b51a72243afc2155e5757e90bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-7.1.1-sources.jar",
          "url": "apkzlib-7.1.1-sources.jar",
          "size": 175862,
          "sha512": "29f221263943836350a9add27db65279ed3104605ea3318e4577f125279c671337ccadb808d49ce68a3da599b704402b3e3b58ddd70bbce35584875dc271f309",
          "sha256": "e3a0d113bb99925a65888fb32a5bf4b058553b4b37493a0863dd63faa92f6f92",
          "sha1": "ebc857329d8e3192d274fcf009a961d1cade7080",
          "md5": "ef16ed08f273fb398afde26b20aefac7"
        }
      ]
    }
  ]
}
