{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-30.1.1.jar",
          "url": "manifest-merger-30.1.1.jar",
          "size": 208014,
          "sha512": "d67b67d22174d21fb4748f8915b4072a0984b3dd1ee4202aefd3e0ac618531f69b8f58662c9e39d3b7eeafdc277887153a3e237c1ca977c2c6b7900253b32a31",
          "sha256": "caf078d76e76a996790520f9952bb4c471cd5809bbe6000b88b54744a8cca830",
          "sha1": "3f5aeb40322dc9908c41d7aabdcb24d7895be552",
          "md5": "1a986b5e7f457863314d8bff3bd5b322"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-30.1.1.jar",
          "url": "manifest-merger-30.1.1.jar",
          "size": 208014,
          "sha512": "d67b67d22174d21fb4748f8915b4072a0984b3dd1ee4202aefd3e0ac618531f69b8f58662c9e39d3b7eeafdc277887153a3e237c1ca977c2c6b7900253b32a31",
          "sha256": "caf078d76e76a996790520f9952bb4c471cd5809bbe6000b88b54744a8cca830",
          "sha1": "3f5aeb40322dc9908c41d7aabdcb24d7895be552",
          "md5": "1a986b5e7f457863314d8bff3bd5b322"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-30.1.1-javadoc.jar",
          "url": "manifest-merger-30.1.1-javadoc.jar",
          "size": 580399,
          "sha512": "0d65e4323858750d1a6f48a9fa5753423f1e6124a6e965a7c3be1f51831a1c6b4b46a0e4c8b265d1f4a462e933f5254297783b2eb090bb6ff3d893b1d75a18a5",
          "sha256": "b1c454670b90f66556b9eadf52af1f372c1e33101ac86de38a071742a9ff44e6",
          "sha1": "7ebc8bbd2f39878706966ed7cafdc1ae2cc72b39",
          "md5": "4934bde3714ba589bafa9189e1e9e6d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-30.1.1-sources.jar",
          "url": "manifest-merger-30.1.1-sources.jar",
          "size": 210197,
          "sha512": "3b01206aed29198f71a025ff07476009240e747e03913f274ab6013405b74c709c9d2632f4b82f49607db777625bee5a6400ed2039420d77b56040dfc74d1f9b",
          "sha256": "adb3d65fd808a4422bd3dc54ab0ccdfd8e9f84b00e02fc0222e5def6eb75e9ad",
          "sha1": "5acda7cf1b0236186c79d7d34edae3cf4dba0a2b",
          "md5": "05148f9d73513520bec01d13d758f73a"
        }
      ]
    }
  ]
}
