{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "7.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-7.1.1.jar",
          "url": "builder-7.1.1.jar",
          "size": 12912518,
          "sha512": "15efcaed2b54fd1f97ec6f9e6e74371bc2fa8e728558e26ae0503d14229a24aaeec58237a0aebc24ec290b02695e84dfcb1804085283a70f5fbda8ac5bcbf901",
          "sha256": "54365b79103e6d8c7fdd7e92b6e8d4437406b70a9f2a56140f3237fe235885d3",
          "sha1": "012bf7a4cd32c4cd3fdc96ed8308e0cbfbe605e2",
          "md5": "d082a5a0e676bc50e087b57d1f24459c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-7.1.1.jar",
          "url": "builder-7.1.1.jar",
          "size": 12912518,
          "sha512": "15efcaed2b54fd1f97ec6f9e6e74371bc2fa8e728558e26ae0503d14229a24aaeec58237a0aebc24ec290b02695e84dfcb1804085283a70f5fbda8ac5bcbf901",
          "sha256": "54365b79103e6d8c7fdd7e92b6e8d4437406b70a9f2a56140f3237fe235885d3",
          "sha1": "012bf7a4cd32c4cd3fdc96ed8308e0cbfbe605e2",
          "md5": "d082a5a0e676bc50e087b57d1f24459c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-7.1.1-javadoc.jar",
          "url": "builder-7.1.1-javadoc.jar",
          "size": 724951,
          "sha512": "1fae5944d59986c77571efdc47d2e533eddd40ed1402ae7062c4310392fdcb9f5261686235aa26e356422062eb92f25e5dc50156764b1742f7a098f8306b0e4d",
          "sha256": "530e94cb4d98738b6ce77a45a5107e551edb2379aabe02cf7853163954cf6c90",
          "sha1": "596817b673bae51641fab91fb97f0b9f68f9c7ca",
          "md5": "be4fb55e5e8a9112e942701d1b9954b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-7.1.1-sources.jar",
          "url": "builder-7.1.1-sources.jar",
          "size": 279172,
          "sha512": "8813e134fcf1eaec3b9cf131350962fddd93974720f79f843fba6e598333dcf64f95cbc89cb38e45cfc9d0f3e997456d4cf42d81359f5718ced66579e4423f0a",
          "sha256": "9354722695500edbecbfec7ed505ce2854d1720911ed65db11bc5bc1b7bdff87",
          "sha1": "809ce7ef6047691f4a645db76693a32b63838019",
          "md5": "264b63f44f625263a96890d2302748a9"
        }
      ]
    }
  ]
}
