{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "sdk-common",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sdk-common-30.1.1.jar",
          "url": "sdk-common-30.1.1.jar",
          "size": 1419233,
          "sha512": "29b6b5036e1eb4c2652c99e88148e2f3db55fe3393b4731ca035db23a77caa0148488830fc5a64b5a6ce6a7de2db4368e13901a129042a523e1c57d10e16d374",
          "sha256": "c5fc3ffdfba0bd5faaf8ba1b4fa9c17c14264cb155dbff66831abd500d2b0698",
          "sha1": "469ad2de6d8386710dac7d0e5e0b106a52f19565",
          "md5": "82855a2c231fc65a1589e3d34c3fe93e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.intellij.deps",
          "module": "trove4j",
          "version": {
            "requires": "1.0.20181211"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "7.0.0-beta04-7396180"
          }
        },
        {
          "group": "xerces",
          "module": "xercesImpl",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-common-30.1.1.jar",
          "url": "sdk-common-30.1.1.jar",
          "size": 1419233,
          "sha512": "29b6b5036e1eb4c2652c99e88148e2f3db55fe3393b4731ca035db23a77caa0148488830fc5a64b5a6ce6a7de2db4368e13901a129042a523e1c57d10e16d374",
          "sha256": "c5fc3ffdfba0bd5faaf8ba1b4fa9c17c14264cb155dbff66831abd500d2b0698",
          "sha1": "469ad2de6d8386710dac7d0e5e0b106a52f19565",
          "md5": "82855a2c231fc65a1589e3d34c3fe93e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-common-30.1.1-javadoc.jar",
          "url": "sdk-common-30.1.1-javadoc.jar",
          "size": 1645538,
          "sha512": "20961bf4141a4443e0959f1afb73f2ca806b69958baf185fce352f32b3e02d1777f941c564aa21ee7971ed8c144e3108d83cfe939a2f6f6348b00e7a858943e4",
          "sha256": "906088c4f01200608d063ce658223e4646ffc8f93bfcfad01f3b858d8c4db38d",
          "sha1": "f1707cf5d5697476eca7c23dfe5ec84c6213b1f5",
          "md5": "905e9a353b22a4302254086a793ce646"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-common-30.1.1-sources.jar",
          "url": "sdk-common-30.1.1-sources.jar",
          "size": 804538,
          "sha512": "36b13ce15fb6a62804ceff9f1d01b807c1742c3dc92074cf9d4b725967b0c520a6dfb92c93f315296311b15ebc153a74fefb4f51310c85d890339bda2065ddb6",
          "sha256": "1add41379baa19a606eaba5ec55f79e3d0cbcc2d0c2414b836d6ccf394c20e40",
          "sha1": "b93c0b8a999535a085651213a0a9f9c894161888",
          "md5": "b95f68ca30da4cef3385b47ba5d7ae01"
        }
      ]
    }
  ]
}
