{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "sdklib",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "30.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdklib-30.1.1.jar",
          "url": "sdklib-30.1.1.jar",
          "size": 690434,
          "sha512": "40538fb37f4123d6eaf73c17fcf02b832600c751fe6b3341dbfbcfa16449e361cae3e4c82d3e88973968c5a2e35693530c2d985257603cc5b8dfd6f7cc7570e2",
          "sha256": "c1af982431f17deb7db068172a0de5b9a2d099843cdee9f899d0367bef6b5cf1",
          "sha1": "8784a5ca3529dfee4ec0e26ed76847c8797c061f",
          "md5": "66104e7810d7c04ccc38e66760f9fabb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "dvlib",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.20"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.10"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "30.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdklib-30.1.1.jar",
          "url": "sdklib-30.1.1.jar",
          "size": 690434,
          "sha512": "40538fb37f4123d6eaf73c17fcf02b832600c751fe6b3341dbfbcfa16449e361cae3e4c82d3e88973968c5a2e35693530c2d985257603cc5b8dfd6f7cc7570e2",
          "sha256": "c1af982431f17deb7db068172a0de5b9a2d099843cdee9f899d0367bef6b5cf1",
          "sha1": "8784a5ca3529dfee4ec0e26ed76847c8797c061f",
          "md5": "66104e7810d7c04ccc38e66760f9fabb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdklib-30.1.1-javadoc.jar",
          "url": "sdklib-30.1.1-javadoc.jar",
          "size": 1177587,
          "sha512": "fcc025f3747d0fabab16353edfd0d42a7626dbb4167cdacd6a11a668222ef2b1503035ccae455a02d67a2b38fa12f82478c299529edc1f1803d613d6b9222f2f",
          "sha256": "5a0a3aad3eadb825b3438953742b88f1ada4dbf7f09af852a32ce2f896c71eb4",
          "sha1": "c5200a8acbf7b243e53315a652bbd9a72d9504bc",
          "md5": "7ef4d85e7248981c736bb33dff1425e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdklib-30.1.1-sources.jar",
          "url": "sdklib-30.1.1-sources.jar",
          "size": 577807,
          "sha512": "23c8dca13a00f3beb608860f11f194bd793862458e7a6666a9e1eda2316cb2178e896d7d35a0d2669fe63b215ad31b00dbfdcacb82cba0e2645306ba27f2494b",
          "sha256": "90340cabc84fc109a6a9a20289cb8c81b5122292ce0fd17edada38ff198c5a2b",
          "sha1": "ef31c938b9595baa84344104854512fd15adad51",
          "md5": "9c3785e70151ee999cea09ad5a83b7b6"
        }
      ]
    }
  ]
}
