{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-retention-proto",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.1.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.1.jar",
          "size": 39328,
          "sha512": "e5420605ba2519a39e5b277f7744c94a6305f8329d6c264741b4d1513bcab60a58f2cc53553bf2104c8336a82f4f6b2f899abe47ac6da2afa689792124e8280b",
          "sha256": "0b8ccff8801f3552da0c8cab54198f1c7f5a6aa6ea32f957d955448306e4dc87",
          "sha1": "74713b52e6a51fe15c2301a00ad887c6c35471ce",
          "md5": "c7f2dac7a6818470140b1615f37f7ca7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.1.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.1.jar",
          "size": 39328,
          "sha512": "e5420605ba2519a39e5b277f7744c94a6305f8329d6c264741b4d1513bcab60a58f2cc53553bf2104c8336a82f4f6b2f899abe47ac6da2afa689792124e8280b",
          "sha256": "0b8ccff8801f3552da0c8cab54198f1c7f5a6aa6ea32f957d955448306e4dc87",
          "sha1": "74713b52e6a51fe15c2301a00ad887c6c35471ce",
          "md5": "c7f2dac7a6818470140b1615f37f7ca7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.1-javadoc.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.1-javadoc.jar",
          "size": 451214,
          "sha512": "185be5350be2e26c7b8abb75c68b9aefb08900f37751efc4ddb88c23e4705514fe0542e66130f9920e68a266150191d77a0981923f97fc18ae90ef33b9a18876",
          "sha256": "b9148512eced43a5e0f1de79b6e45fe0f134cdf8bb6ffcd93316935def19757e",
          "sha1": "a6120961c56cce17d6cff7ac0e0e364976653861",
          "md5": "408e80ddddddfd2ac7189758fdf7b30d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-proto-30.1.1-sources.jar",
          "url": "android-test-plugin-host-retention-proto-30.1.1-sources.jar",
          "size": 16525,
          "sha512": "5b68fbb6e7c730bcb208c242ab4249fd6ab2d2ff13dce77e50093ebcf4e07bde4e369cbf951fb67802788813210e40950582f47a9f5b118e5e42e13d500eb0b2",
          "sha256": "a772a35431eebf5d94c42a56a08d4781f4f20b64da8e8e54de171ecdc16b85ed",
          "sha1": "9ccfb6990234b27dd139b6ed2bd79d755c5417bf",
          "md5": "1c5aecd906ab8ae1e98b3cc5cc915d2f"
        }
      ]
    }
  ]
}
