{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-device-provider-ddmlib-proto",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-proto-30.1.1.jar",
          "url": "android-device-provider-ddmlib-proto-30.1.1.jar",
          "size": 19442,
          "sha512": "a30ee4d1e48fa80936b5ba95ccd93eb6e4cd66e5583d97075ac5cd79b0975f53e964b76f30f4b49b67a0fdc1c9ffbb129adf44895b1bd3da7ae922206278aa0f",
          "sha256": "1c36103227567264859bf26533ac2a8481eabd5f4e8fec0c18a95d267bf48b38",
          "sha1": "da85a350f32fc76494cc5f2998e47f0e5b9a120b",
          "md5": "e7a62d551f6f3345bd0a966de625a583"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-device-provider-ddmlib-proto-30.1.1.jar",
          "url": "android-device-provider-ddmlib-proto-30.1.1.jar",
          "size": 19442,
          "sha512": "a30ee4d1e48fa80936b5ba95ccd93eb6e4cd66e5583d97075ac5cd79b0975f53e964b76f30f4b49b67a0fdc1c9ffbb129adf44895b1bd3da7ae922206278aa0f",
          "sha256": "1c36103227567264859bf26533ac2a8481eabd5f4e8fec0c18a95d267bf48b38",
          "sha1": "da85a350f32fc76494cc5f2998e47f0e5b9a120b",
          "md5": "e7a62d551f6f3345bd0a966de625a583"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-proto-30.1.1-javadoc.jar",
          "url": "android-device-provider-ddmlib-proto-30.1.1-javadoc.jar",
          "size": 418149,
          "sha512": "ffbef205387b379f8f3709e3fd9e996a3140fa59498c902cc5c4651d1b278599536fc2092821e81d91573e45dad86d34ef5aa42dab1a8f5972b6cb1b5ef6ccec",
          "sha256": "cecc95cc23fd56603d073e1a3e957fb74cb74ee21b4aee0ff7bfb98cc72be7f4",
          "sha1": "7da35ee29f95111a5356815910d155bfa274b130",
          "md5": "2bfa7f2f2bb0bbbcd7b422ec6ac4f8d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-proto-30.1.1-sources.jar",
          "url": "android-device-provider-ddmlib-proto-30.1.1-sources.jar",
          "size": 9899,
          "sha512": "e026e7d5db6d326b3755eadc336a54074f8972e53dee4f02f67fa86292f6bb417c4089d5de878612dba7553818378b32c80c65e53b099e806521381e815d1c4a",
          "sha256": "74e5b175607e14499ecb4fb73a156b6ff0ecee4534da2712572eba0cc5ea32a5",
          "sha1": "d8d08b9b3e937448231e0ba40edb0dd090e17ca5",
          "md5": "1cf0de322cb5eeb951b8ba6bef87219a"
        }
      ]
    }
  ]
}
