{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aapt2-proto",
    "version": "7.1.1-7984345",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aapt2-proto-7.1.1-7984345.jar",
          "url": "aapt2-proto-7.1.1-7984345.jar",
          "size": 747666,
          "sha512": "77f98036b72805143292c748d642f691a05a079dacaf02fb6263f22cb9fde6f14674cb3c1c44e14eca1928a90158be0691975cd8ff6718f3382b1e307e4e1ab2",
          "sha256": "a27393d0263efa19f784364bc7f7eea8f088996e853b8399ac38f7e227483710",
          "sha1": "4a11f7e73338183615aed9e6ee8af6a3c022f193",
          "md5": "ac35454a434537380f1cf45d5e5f4632"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "aapt2-proto-7.1.1-7984345.jar",
          "url": "aapt2-proto-7.1.1-7984345.jar",
          "size": 747666,
          "sha512": "77f98036b72805143292c748d642f691a05a079dacaf02fb6263f22cb9fde6f14674cb3c1c44e14eca1928a90158be0691975cd8ff6718f3382b1e307e4e1ab2",
          "sha256": "a27393d0263efa19f784364bc7f7eea8f088996e853b8399ac38f7e227483710",
          "sha1": "4a11f7e73338183615aed9e6ee8af6a3c022f193",
          "md5": "ac35454a434537380f1cf45d5e5f4632"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-7.1.1-7984345-javadoc.jar",
          "url": "aapt2-proto-7.1.1-7984345-javadoc.jar",
          "size": 1433076,
          "sha512": "1e0be897fb29a97182403138631cd63c7b1234b7231208e48ab87dd9a64ef8ccf81a532b9cdb6532bb70691de74116d9f4ad0929cd5835abb5d0ec08c130ba60",
          "sha256": "aaf97fd759d89ffa6a4ea9d1c41e0e0d9a3e8cb02b126e8a4cefb3ef9e268fa8",
          "sha1": "b16d5ffbf816cb724d3c56bce4702759b7534adf",
          "md5": "021cbb83cc8c296e0e7217f299d94c44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-7.1.1-7984345-sources.jar",
          "url": "aapt2-proto-7.1.1-7984345-sources.jar",
          "size": 200643,
          "sha512": "d5c195c45c0835a22554977dc1142828a034b9c61c4a7efa3d437aa07a6ff2f1040db5a0fb42d273f0d2302dc43b3752168aafd4bafbc81e0096174f1efec2bc",
          "sha256": "41231bf8a1195d26bf27e37adf6cb2024a38ec1fbdbd0cf17e66a3c5c0f912b4",
          "sha1": "cd69c6ac449124afcf4e324205f9116020a4842c",
          "md5": "b59742e36ce78b7027a04818b382dc66"
        }
      ]
    }
  ]
}
