{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "repository",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "repository-30.1.1.jar",
          "url": "repository-30.1.1.jar",
          "size": 236840,
          "sha512": "7cb8164c5fc8c8c19bb86701ff4f39a9764dc2aab39b3bc83bf3fb85bcaacd0e5773522cf47f8ed571e4a9307890bb61ebe200bd337e41b37e67dabf2a11cfc7",
          "sha256": "cd499364de7e5a03e4da986ac45afa7021093efb3dc815f895674c5e9f0ebf12",
          "sha1": "e7e4a2ee570f715502ae5f77a1b5f9d5331f8902",
          "md5": "ddd6b3fdf552af1ae4074eea4cd89299"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.sun.activation",
          "module": "javax.activation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.20"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.jimfs",
          "module": "jimfs",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "repository-30.1.1.jar",
          "url": "repository-30.1.1.jar",
          "size": 236840,
          "sha512": "7cb8164c5fc8c8c19bb86701ff4f39a9764dc2aab39b3bc83bf3fb85bcaacd0e5773522cf47f8ed571e4a9307890bb61ebe200bd337e41b37e67dabf2a11cfc7",
          "sha256": "cd499364de7e5a03e4da986ac45afa7021093efb3dc815f895674c5e9f0ebf12",
          "sha1": "e7e4a2ee570f715502ae5f77a1b5f9d5331f8902",
          "md5": "ddd6b3fdf552af1ae4074eea4cd89299"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "repository-30.1.1-javadoc.jar",
          "url": "repository-30.1.1-javadoc.jar",
          "size": 969349,
          "sha512": "405935608f7fc0a0cd015f034db890189836968edbad4f680247779a07eae835c34c59703fbbff5e1c118d6c5aadc1e4d02e8e42acbe1f96451e9d6e4aef5ec4",
          "sha256": "97702d22ce8fa2cdfbd971b59eac033c197a6545617fa3c868ffc5fdfd08e7fb",
          "sha1": "dce754551f1d77a2240f34484aebe0e2612ba6b4",
          "md5": "465408af848b906974a4749caec7635c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "repository-30.1.1-sources.jar",
          "url": "repository-30.1.1-sources.jar",
          "size": 381549,
          "sha512": "000fce257f6f06b74161550f8f5c6b6047ea2c615fe413a34a337b503986bb55a6af65562f06f45acf42f034cda7d6517d9a7211cf6da5faaa94f8f025399463",
          "sha256": "6fb80a882d2f243aafc3b24cdadbc6bf7e44d8023e18161db54e5097a519a073",
          "sha1": "0de0f33a8b003a929b19ecb9c7521ea724add00a",
          "md5": "42d1f6406d26b17b5aded7e4f1c13f9f"
        }
      ]
    }
  ]
}
