{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.analytics-library",
    "module": "tracker",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "30.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "tracker-30.1.1.jar",
          "url": "tracker-30.1.1.jar",
          "size": 40461,
          "sha512": "3a5fb5d47a9eb3bf3814530a81118e9dbb6573d3c720370579e20f90637b633fcd1bb5ab826652f72e9c1b26b202b5dc3ec9d47ada714b39171ac44f4d1b738c",
          "sha256": "484077737412f66e3066be2d439dfed37cd2cf4fe1369863b0cf86fd9a0c07c9",
          "sha1": "40523b372b2efdb6371ad8f084fe54b6d5abfc32",
          "md5": "89e7370de85b823e243fb80ba922f8f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "30.1.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "30.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "tracker-30.1.1.jar",
          "url": "tracker-30.1.1.jar",
          "size": 40461,
          "sha512": "3a5fb5d47a9eb3bf3814530a81118e9dbb6573d3c720370579e20f90637b633fcd1bb5ab826652f72e9c1b26b202b5dc3ec9d47ada714b39171ac44f4d1b738c",
          "sha256": "484077737412f66e3066be2d439dfed37cd2cf4fe1369863b0cf86fd9a0c07c9",
          "sha1": "40523b372b2efdb6371ad8f084fe54b6d5abfc32",
          "md5": "89e7370de85b823e243fb80ba922f8f4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracker-30.1.1-javadoc.jar",
          "url": "tracker-30.1.1-javadoc.jar",
          "size": 402622,
          "sha512": "0ef243e039dad8d2ccf1b42b86494f1e4f3fd751f6159a080c44d05a23c0833001b620ffa47a1bb5ed54a0818640b2582a285417f391610c300f2a738fd4eac3",
          "sha256": "46b7e0391a99bcaff26f190303b9c757511e8f4d61478e3142d98bb3db3b0353",
          "sha1": "2a9b173486fd891029452468849b179d3eacefda",
          "md5": "d59b36be620756c29eec01bf18e4b645"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracker-30.1.1-sources.jar",
          "url": "tracker-30.1.1-sources.jar",
          "size": 18388,
          "sha512": "443c079fd7e7d7269d7c968a93b5deacdde6cb2a97a2cefab8a10f7b82f1a1126d6ad54d6210060082b20073f69f1a0ff484aa2374afd838d1faa7d6ea9ecfab",
          "sha256": "5431d9a73a9d4587312cba8b76887ccc8a570df6d1a3d51d7de1b121bc46b9aa",
          "sha1": "64fdee07993130d60a67bdbdb818b2f1d93990f4",
          "md5": "2d87e00ddae43061e769f0d0db3942d5"
        }
      ]
    }
  ]
}
